### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by husk0808** [puenktchen/PeopleBackupPlugin#1]
I hope the planned task contains (Run Full Restore of People)

**Comment by puenktchen** [comment]
What do you mean with "planned"?
Currently there's only one task and that is for creating the backup. A scheduled task for a restore doesn't make sense to me.

**Comment by husk0808** [comment]
Planning Task - Timed Restore Information
In fact, the character information of my country is not English. I have to build information. According to restore information, I will need to ask if I want to ask if I want to ask if I want to ask. I can't add a task.

**Comment by puenktchen** [comment]
Because the upcoming Emby 4.6.x reinvents the people folder under metadata,
this plugin is then outdated and i don't plan to make any changes anymore for Emby 4.5.x .
